name: Update README with HTML links

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate README
        run: |
          BASE_URL="https://armorednightmare.github.io/arcdps_shares"
          echo "# arcdps_shares" > README.md
          echo "" >> README.md
          echo "## Available HTML Files" >> README.md
          echo "" >> README.md

          find . -maxdepth 1 -type f -name "*.html" | sort | while read file; do
            filename=$(basename "$file")
            url="$BASE_URL/$filename"
            echo "- [$filename]($url)" >> README.md
          done

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README with HTML links"
